#! /bin/sh
for f in "$1"/*; do
  if [ -f "$f" ]; then
    SIZE="$(wc -w "${f}" | cut -f1)"
    FILE="$(ls -lh "${f}" | awk '{print $5}')"
    echo "Processing $f file..."
    echo "Word Count: $SIZE\nFile Size: $FILE\n"
  fi
done
